### PR TITLE
Reformat to plug in based system

### PR DESCRIPTION
**Pull request by FriendlyGecko**
This PR makes the bashflix script iterate through a directory of plugins to determine which resources to query for media. This will simplify the addition of other resources as the base script will not need to be updated and a bash script plugin that outputs a proper magnet link will be the only necessary component to add these other resources. This will also allow users to pick and choose what resources they access as well as what order to search (potential to add flag to allow selection of repo). Included is a folder of three plugins I have already created (a couple were reformatted from original bashflix to work with this).

I will need to double check it as I did this work months ago and forgot to submit a PR until I got an email about my last one.

This PR will allow closure of: #15 & #18

### CODE REVIEW

**Comment by FriendlyGecko** [comment]
This needs more work before it is ready to be merged. I realized it used an older bashflix script so it is being reformatted to work properly.

**Comment by FriendlyGecko** [comment]
Cleaned up the script and tested it, should be ready for a look over

**Comment by 0zz4r** [comment]
ia and we-get doesn't seem to work unfortunately. thank you anyway!

**Comment by FriendlyGecko** [comment]
Ok, I will continue the plug-in variation as my own fork. If I find any fixes or improvements that can be upstreamed I will continue to submit them.

**Pull request closed without merging**
